import time
from timetable.models import Term, ScheduledUnit, Conflict, Cohort, CurriculumUnit, Room, Period, Trainer
term = Term.objects.get(id="2cf9912b-b640-40b2-be29-f5989810af4f")
t0=time.time()
ScheduledUnit.objects.filter(term=term,status="DRAFT").delete()
print("delete drafts:",round(time.time()-t0,2))
t1=time.time()
Conflict.objects.filter(term=term).delete()
print("delete conflicts:",round(time.time()-t1,2))
t2=time.time()
cohorts=list(Cohort.objects.filter(term=term,is_active=True).select_related("programme"))
print("load cohorts:",round(time.time()-t2,2),len(cohorts))
t3=time.time()
for c in cohorts:
    t4=time.time()
    u=list(CurriculumUnit.objects.filter(programme=c.programme,term_number=c.current_term,is_active=True).prefetch_related("qualified_trainers"))
    print(c.name,len(u),round(time.time()-t4,3))
t5=time.time()
rooms=list(Room.objects.filter(is_active=True))
periods=list(Period.objects.filter(term=term,is_break=False).order_by("order"))
print("rooms+periods:",round(time.time()-t5,2))
t6=time.time()
trainers=list(Trainer.objects.filter(is_active=True))
print("trainers:",round(time.time()-t6,2))