# Generated by Django 6.0.4 on 2026-04-23 21:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=60)),
                ('days_of_week', models.JSONField(default=list, help_text='Ordered list e.g. ["MON","TUE","WED","THU","FRI"]')),
                ('allow_back_to_back', models.BooleanField(default=True, help_text='Whether consecutive periods for the same trainer are allowed')),
                ('max_periods_per_day', models.PositiveSmallIntegerField(default=4)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('hod', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='timetable.institution')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Period 1" or "Morning Block"', max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField()),
                ('is_break', models.BooleanField(default=False, help_text='Mark breaks so the scheduler skips them')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.institution')),
            ],
            options={
                'ordering': ['institution', 'order'],
                'unique_together': {('institution', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('level', models.CharField(choices=[('CERT', 'Certificate'), ('DIP', 'Diploma'), ('HDIP', 'Higher Diploma'), ('DEG', 'Degree'), ('PG_DIP', 'Postgraduate Diploma'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('OTHER', 'Other')], max_length=10)),
                ('total_terms', models.PositiveSmallIntegerField(default=4, help_text='Total number of teaching terms in the programme')),
                ('sharing_group', models.CharField(blank=True, db_index=True, help_text='Set the same value on programmes that share units.', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='timetable.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_number', models.PositiveSmallIntegerField(help_text='Which term (1 = first term of programme)')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project')], default='CORE', max_length=10)),
                ('credit_hours', models.PositiveSmallIntegerField(default=3)),
                ('periods_per_week', models.PositiveSmallIntegerField(default=1, help_text='1 = single period, 2 = double period (consecutive)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_units', to='timetable.programme')),
            ],
            options={
                'ordering': ['programme', 'term_number', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('start_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('current_term', models.PositiveSmallIntegerField(default=1, help_text='Which programme term this cohort is currently in')),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='timetable.programme')),
            ],
            options={
                'ordering': ['-start_year', '-start_month', 'programme'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('COMPUTER', 'Computer Lab'), ('CLINICAL', 'Clinical Lab'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar Room'), ('HALL', 'Lecture Hall'), ('ONLINE', 'Online / Virtual'), ('OTHER', 'Other')], max_length=10)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(default=list, help_text='e.g. ["projector","whiteboard","aircon"]')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='timetable.institution')),
            ],
            options={
                'ordering': ['building', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teaching_weeks', models.PositiveSmallIntegerField(default=14)),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='timetable.institution')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='NOT_STARTED', max_length=12)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='timetable.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='timetable.curriculumunit')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='timetable.term')),
            ],
            options={
                'ordering': ['cohort', 'curriculum_unit__term_number', 'curriculum_unit__position'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('GENERATE', 'Timetable Generated'), ('PUBLISH', 'Timetable Published'), ('DELETE', 'Timetable Deleted'), ('EDIT', 'Entry Edited'), ('CANCEL', 'Entry Cancelled'), ('RESOLVE', 'Conflict Resolved'), ('PROGRESS', 'Progress Updated')], max_length=10)),
                ('description', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='timetable.term')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employment_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('VS', 'Visiting'), ('CT', 'Contract')], default='FT', max_length=2)),
                ('max_periods_per_week', models.PositiveSmallIntegerField(default=20, help_text='Maximum teaching periods (not hours) per week')),
                ('available_days', models.JSONField(default=list, help_text='Specific days available, e.g. ["MON","WED","FRI"]. Leave empty for FT staff (means all institution days).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='timetable.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='timetable.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=3)),
                ('sequence', models.PositiveSmallIntegerField(default=0, help_text='0 = single period; 1 = first of a pair; 2 = second of a pair')),
                ('is_combined', models.BooleanField(default=False)),
                ('combined_key', models.CharField(blank=True, db_index=True, help_text='Shared key linking rows for combined cohorts', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.curriculumunit')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.period')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.term')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_units', to='timetable.trainer')),
            ],
            options={
                'ordering': ['day', 'period__order', 'cohort'],
            },
        ),
        migrations.AddField(
            model_name='curriculumunit',
            name='qualified_trainers',
            field=models.ManyToManyField(blank=True, related_name='qualified_units', to='timetable.trainer'),
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('UNIT', 'Curriculum Unit'), ('TRAINER', 'Trainer'), ('ROOM', 'Room'), ('COHORT', 'Cohort')], max_length=8)),
                ('rule', models.CharField(choices=[('PIN_DAY_PERIOD', 'Pin to day + period'), ('PIN_DAY', 'Pin to day (any period)'), ('PREFERRED_ROOM', 'Preferred room'), ('AVOID_DAY', 'Avoid day'), ('AVOID_PERIOD', 'Avoid period'), ('BACK_TO_BACK', 'Schedule back-to-back'), ('MAX_PER_DAY', 'Max periods per day')], max_length=20)),
                ('is_hard', models.BooleanField(default=True, help_text='Hard constraints must be satisfied. Soft = try but can skip.')),
                ('parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.curriculumunit')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.room')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.trainer')),
            ],
            options={
                'ordering': ['-is_hard', 'scope', 'rule'],
            },
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(choices=[('TRAINER_CLASH', 'Trainer double-booked'), ('ROOM_CLASH', 'Room double-booked'), ('COHORT_CLASH', 'Cohort double-booked'), ('NO_TRAINER', 'No qualified trainer'), ('NO_ROOM', 'No suitable room'), ('CONSTRAINT', 'Constraint violated'), ('CAPACITY', 'Room capacity exceeded')], max_length=15)),
                ('severity', models.CharField(choices=[('HIGH', 'High – blocks publishing'), ('MEDIUM', 'Medium – possible issue'), ('LOW', 'Low – informational')], default='HIGH', max_length=6)),
                ('description', models.TextField()),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('OVERRIDDEN', 'Overridden'), ('IGNORED', 'Ignored')], default='PENDING', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.curriculumunit')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.room')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='timetable.term')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.trainer')),
            ],
            options={
                'ordering': ['-created_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='TrainerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=3)),
                ('is_available', models.BooleanField(default=False, help_text='False = BLOCKED, True = explicitly available (for soft preferences)')),
                ('reason', models.CharField(choices=[('LEAVE', 'Annual Leave'), ('SICK', 'Sick Leave'), ('TRAINING', 'Training / Conference'), ('ADMIN', 'Administrative Duty'), ('UNAVAILABLE', 'Unavailable (no reason)'), ('PREFERRED', 'Preferred slot (soft)')], default='UNAVAILABLE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, help_text='Leave blank to block the entire day', null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.period')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_availability', to='timetable.term')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='timetable.trainer')),
            ],
            options={
                'ordering': ['trainer', 'day', 'period__order'],
            },
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['programme', 'is_active'], name='timetable_c_program_f62cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['current_term'], name='timetable_c_current_a87c24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohort',
            unique_together={('programme', 'start_year', 'start_month')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'capacity'], name='timetable_r_room_ty_37de1a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['institution', 'is_active'], name='timetable_r_institu_8b6e2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('institution', 'code')},
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['institution', 'is_current'], name='timetable_t_institu_dcd235_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['start_date', 'end_date'], name='timetable_t_start_d_e65d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='progressrecord',
            index=models.Index(fields=['cohort', 'status'], name='timetable_p_cohort__d30619_idx'),
        ),
        migrations.AddIndex(
            model_name='progressrecord',
            index=models.Index(fields=['curriculum_unit', 'status'], name='timetable_p_curricu_71fd17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together={('cohort', 'curriculum_unit', 'term')},
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['institution', 'is_active'], name='timetable_t_institu_2ed569_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['department'], name='timetable_t_departm_2c2c56_idx'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['employment_type'], name='timetable_t_employm_6a853b_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledunit',
            index=models.Index(fields=['term', 'status'], name='timetable_s_term_id_2ea588_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledunit',
            index=models.Index(fields=['trainer', 'day', 'period'], name='timetable_s_trainer_f5d99a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledunit',
            index=models.Index(fields=['cohort', 'day', 'period'], name='timetable_s_cohort__ce20a4_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledunit',
            index=models.Index(fields=['room', 'day', 'period'], name='timetable_s_room_id_b555d2_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledunit',
            index=models.Index(fields=['combined_key'], name='timetable_s_combine_90c095_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledunit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('term', 'trainer', 'day', 'period'), name='uniq_trainer_slot_published'),
        ),
        migrations.AddConstraint(
            model_name='scheduledunit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('term', 'cohort', 'day', 'period'), name='uniq_cohort_slot_published'),
        ),
        migrations.AddConstraint(
            model_name='scheduledunit',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('term', 'room', 'day', 'period'), name='uniq_room_slot_published'),
        ),
        migrations.AddIndex(
            model_name='curriculumunit',
            index=models.Index(fields=['programme', 'term_number'], name='timetable_c_program_5d255a_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumunit',
            index=models.Index(fields=['code'], name='timetable_c_code_40e96c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumunit',
            unique_together={('programme', 'code')},
        ),
        migrations.AddIndex(
            model_name='constraint',
            index=models.Index(fields=['curriculum_unit', 'is_active'], name='timetable_c_curricu_9bc8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='constraint',
            index=models.Index(fields=['trainer', 'is_active'], name='timetable_c_trainer_8267fa_idx'),
        ),
        migrations.AddIndex(
            model_name='constraint',
            index=models.Index(fields=['cohort', 'is_active'], name='timetable_c_cohort__ed90c0_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['term', 'resolution_status'], name='timetable_c_term_id_c107d0_idx'),
        ),
        migrations.AddIndex(
            model_name='conflict',
            index=models.Index(fields=['conflict_type', 'severity'], name='timetable_c_conflic_ac3ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='traineravailability',
            index=models.Index(fields=['trainer', 'term'], name='timetable_t_trainer_1c9eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='traineravailability',
            index=models.Index(fields=['day', 'is_available'], name='timetable_t_day_909ce3_idx'),
        ),
    ]
