# Generated by Django 6.0.4 on 2026-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='add_drop_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='withdrawal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
