# Generated by Django 6.0.4 on 2026-04-25 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High Ã¢â‚¬â€œ blocks publishing'), ('MEDIUM', 'Medium Ã¢â‚¬â€œ possible issue'), ('LOW', 'Low Ã¢â‚¬â€œ informational')], default='HIGH', max_length=6),
        ),
        migrations.CreateModel(
            name='CurriculumUnitTrainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('OUTSOURCED', 'Outsourced')], default='INTERNAL', max_length=10)),
                ('label', models.CharField(blank=True, help_text="Optional custom label e.g. 'HOD Physics dept'", max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_trainers', to='timetable.curriculumunit')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_assignments', to='timetable.trainer')),
            ],
            options={
                'ordering': ['trainer_type', 'trainer__last_name'],
                'unique_together': {('curriculum_unit', 'trainer')},
            },
        ),
        migrations.RemoveField(
            model_name='curriculumunit',
            name='qualified_trainers',
        ),
        migrations.AddField(
            model_name='curriculumunit',
            name='qualified_trainers',
            field=models.ManyToManyField(blank=True, related_name='qualified_units', through='timetable.CurriculumUnitTrainer', to='timetable.trainer'),
        ),
    ]

