# Generated by Django 6.0.4 on 2026-04-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_semester_add_drop_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='add_drop_deadline',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='withdrawal_deadline',
        ),
    ]
