# Generated by Django 6.0.4 on 2026-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_add_curriculum_unit_trainer_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumunit',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='Unit is taught by an external/outsourced trainer'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High â€“ blocks publishing'), ('MEDIUM', 'Medium â€“ possible issue'), ('LOW', 'Low â€“ informational')], default='HIGH', max_length=6),
        ),
    ]
