# Generated by Django 6.0.4 on 2026-05-01 13:02

from django.db import migrations

from timetable import models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_fix_combined_slot_indexes'),
    ]

    operations = [
    migrations.AddConstraint(
        model_name='scheduledunit',
        constraint=models.UniqueConstraint(
            fields=['term', 'trainer', 'day', 'period'],
            name='uniq_trainer_slot_draft',
            condition=models.Q(status='DRAFT'),
        ),
    ),
    migrations.AddConstraint(
        model_name='scheduledunit',
        constraint=models.UniqueConstraint(
            fields=['term', 'cohort', 'day', 'period'],
            name='uniq_cohort_slot_draft',
            condition=models.Q(status='DRAFT'),
        ),
    ),
    migrations.AddConstraint(
        model_name='scheduledunit',
        constraint=models.UniqueConstraint(
            fields=['term', 'room', 'day', 'period'],
            name='uniq_room_slot_draft',
            condition=models.Q(status='DRAFT'),
        ),
    ),
]