# Generated by Django 6.0.4 on 2026-05-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_add_draft_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledunit',
            name='uniq_trainer_slot_draft',
        ),
        migrations.RemoveConstraint(
            model_name='scheduledunit',
            name='uniq_cohort_slot_draft',
        ),
        migrations.RemoveConstraint(
            model_name='scheduledunit',
            name='uniq_room_slot_draft',
        ),
        migrations.AlterField(
            model_name='scheduledunit',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_units', to='timetable.trainer'),
        ),
    ]
