# Generated by Django 6.0.4 on 2026-05-03 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_allow_null_trainer_scheduled_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='college_semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semester 1 (Jan–Apr)'), (2, 'Semester 2 (May–Aug)'), (3, 'Semester 3 (Sep–Dec)')], help_text='Which college-wide semester: 1=Jan, 2=May, 3=Sep', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='college_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Calendar year this college semester belongs to, e.g. 2026', null=True),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['college_year', 'college_semester'], name='timetable_t_college_f10baf_idx'),
        ),
    ]
