# Generated by Django 6.0.4 on 2026-05-03 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_term_college_semester_term_college_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='current_term',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cached from latest active enrolment. Do not edit directly.'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High — blocks publishing'), ('MEDIUM', 'Medium — possible issue'), ('LOW', 'Low — informational')], default='HIGH', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='progressrecord',
            unique_together={('cohort', 'curriculum_unit')},
        ),
        migrations.CreateModel(
            name='CohortEnrolment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme_term', models.PositiveSmallIntegerField(help_text='Which term of their programme this cohort studies this semester')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='timetable.cohort')),
                ('college_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='timetable.term')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['college_term__start_date', 'cohort__name'],
            },
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='enrolment',
            field=models.ForeignKey(blank=True, help_text='The enrolment period during which this unit was studied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='timetable.cohortenrolment'),
        ),
        migrations.AddIndex(
            model_name='progressrecord',
            index=models.Index(fields=['enrolment'], name='timetable_p_enrolme_02fd2d_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortenrolment',
            index=models.Index(fields=['cohort', 'status'], name='timetable_c_cohort__5f83fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortenrolment',
            index=models.Index(fields=['college_term', 'status'], name='timetable_c_college_2c573f_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortenrolment',
            index=models.Index(fields=['programme_term'], name='timetable_c_program_ca9b80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cohortenrolment',
            unique_together={('cohort', 'college_term')},
        ),
    ]
