# Generated by Django 6.0.4 on 2026-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_cohort_current_term_alter_conflict_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='attachment_term',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Which term number is the attachment/industrial placement', null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
