# Generated by Django 6.0.4 on 2026-05-07 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_programme_attachment_term_programme_has_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermTrainerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='timetable.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('curriculum_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_assignments', to='timetable.curriculumunit')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='timetable.term')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_assignments', to='timetable.trainer')),
            ],
            options={
                'ordering': ['term', 'cohort', 'curriculum_unit'],
                'indexes': [models.Index(fields=['term', 'trainer'], name='timetable_tta_term_trainer_idx'), models.Index(fields=['term', 'cohort'], name='timetable_tta_term_cohort_idx')],
                'constraints': [models.UniqueConstraint(fields=('term', 'cohort', 'curriculum_unit'), name='uniq_term_cohort_unit_assignment')],
            },
        ),
    ]
