# Generated by Django 6.0.4 on 2026-05-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_termtrainerassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumunit',
            name='session_pattern',
            field=models.CharField(choices=[('SPLIT', 'Split — one session per day across multiple days'), ('BLOCK', 'Block — consecutive periods on the same day')], default='SPLIT', help_text='SPLIT = one session per day; BLOCK = consecutive double period', max_length=5),
        ),
    ]
