# Generated by Django 6.0.4 on 2026-05-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_curriculumunit_session_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('GENERATE', 'Timetable Generated'), ('PUBLISH', 'Timetable Published'), ('REVERT', 'Timetable Reverted to Draft'), ('DELETE', 'Timetable Deleted'), ('EDIT', 'Entry Edited'), ('CANCEL', 'Entry Cancelled'), ('RESOLVE', 'Conflict Resolved'), ('PROGRESS', 'Progress Updated')], max_length=10),
        ),
    ]
